services:
  mongo1:
    image: mongo:8.0
    container_name: mongo1
    hostname: mongo1
    restart: unless-stopped
    # 指定内部运行端口为 27017
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27017:27017"
    volumes:
      - mongo1_data:/data/db
    networks:
      - mongodb-network

  mongo2:
    image: mongo:8.0
    container_name: mongo2
    hostname: mongo2
    restart: unless-stopped
    # 指定内部运行端口为 27018
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--port", "27018"]
    ports:
      - "27018:27018"
    volumes:
      - mongo2_data:/data/db
    networks:
      - mongodb-network

  mongo3:
    image: mongo:8.0
    container_name: mongo3
    hostname: mongo3
    restart: unless-stopped
    # 指定内部运行端口为 27019
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--port", "27019"]
    ports:
      - "27019:27019"
    volumes:
      - mongo3_data:/data/db
    networks:
      - mongodb-network

networks:
  mongodb-network:
    driver: bridge

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data: